name: dockerscoutci

on:
  push:
    branches:
      - master

jobs:
  stage1:
    if: false
    runs-on: ubuntu-latest
    environment: dockerenv
    # env: 
    #       username: ${{ secrets.USERNAME }}
    #       password: ${{ secrets.PASSWORD }}
    steps:
      # - name: demo
      #   run: echo "hello world"
      - name: checkout-git
        uses: actions/checkout@v4
      - name: docker login
        uses: docker/login-action@v3.4.0
        with: 
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags:  ${{ secrets.USERNAME }}/app:latest

      - name: using docker scout to get venrabiklities
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ secrets.USERNAME }}/app:latest
          sarif-file: sarif.output.json
          summary: true

      - name: Upload SARIF result
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sarif.output.json
          
  
  # JOB2        
  sonar-scan:
    if : False
    runs-on: ubuntu-latest
    environment: sonarenv   # <-- this job uses sonarenv
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

        with:
          args: >
            -Dsonar.projectKey=BONAPART1990_pygoat
            -Dsonar.organization=bonapart1990

  # JOB3        
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
 
      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'config'
          scan-ref: "./terraform-IAC"
          hide-progress: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0'
          # severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
      
      
