name: dockerscoutci

on:
  push:
    branches:
      - master

jobs:
  stage1:
    if: false
    runs-on: ubuntu-latest
    environment: dockerenv
    # env: 
    #       username: ${{ secrets.USERNAME }}
    #       password: ${{ secrets.PASSWORD }}
    steps:
      # - name: demo
      #   run: echo "hello world"
      - name: checkout-git
        uses: actions/checkout@v4
      - name: docker login
        uses: docker/login-action@v3.4.0
        with: 
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags:  ${{ secrets.USERNAME }}/app:latest

      - name: using docker scout to get venrabiklities
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ secrets.USERNAME }}/app:latest
          sarif-file: sarif.output.json
          summary: true

      - name: Upload SARIF result
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sarif.output.json
          
  
  # JOB2        
  sonar-scan:
    runs-on: ubuntu-latest
    environment: sonarenv   # <-- this job uses sonarenv
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
