name: dockerscoutci

on:
  push:
    branches:
      - master

jobs:
  stage1:
    runs-on: ubuntu-latest

    steps:
      # - name: demo
      #   run: echo "hello world"
      - name: checkout-git
        uses: actions/checkout@v4