name: dockerscoutci

on:
  push:
    branches:
      - master

jobs:
  stage1:
    runs-on: ubuntu-latest
    environment: dockerenv
    env: 
          username: {{ dockerenv.USERNAME }}
          password: {{ dockerenv.PASSWORD }}
    steps:
      # - name: demo
      #   run: echo "hello world"
      - name: checkout-git
        uses: actions/checkout@v4
      - name: docker login
        uses: docker/login-action@v3.4.0
        with: 
          username: {{ env.USERNAME }}
          password: {{ env.PASSWORD }}
          
          
          
